apiVersion: v1
kind: Service
metadata:
    name:  myapp-service

    #namespace: dev
spec:
    type: LoadBalancer
    ports:
     - targetPort: 80
       port: 80
       nodePort: 3008
    selector:
       app: my-app
       type: front-end # Utilizado para vincular o pod ai serviço
         